title: AI-Z
description: GPU usage graph on the command-line, AI benchmarks
show_downloads: true
google_analytics: UA-136781191-2
theme: jekyll-theme-hacker

email: mathieu.poliquin@gmail.com
url: "https://www.ai-z.org"