title: AI-Z
description: GPU usage graph on the command-line
show_downloads: false
google_analytics: UA-136781191-2
theme: jekyll-theme-hacker

email: mathieu.poliquin@gmail.com
url: "https://www.ai-z.org"

github:
  repository_url: https://github.com/ai-z/ai-z