title: AI-Z
description: GPU usage graph in the terminal for AMD and NVIDIA GPUs
show_downloads: true
google_analytics: UA-136781191-2
logo: assets/logo.png

email: mathieu.poliquin@gmail.com
url: "https://www.ai-z.org"

github:
  repository_url: https://github.com/ai-z/ai-z

remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap